### ISSUE TITLE
[Technical Issue] The implementation of MeanRecall Metric may be wrong.

### ISSUE THREAD

**Issue by putao537** [sayaknag/unbiasedSGG#1]
As presented in evaluation_recall.py, in line 52 and lines 259-260, the recall of total predicates is computed by averaging the total recall on each frame. These codes are correct since them are adpot from previous work STTran [1].

However, in the author's implementation, the recall_hit and recall_count on different frames are summed to compute the recall of each predicate, which is wrong. In this way, you merely obtain the "mean recall" on overall frames, not on each frame, which is conflict from original work.

[1] Spatial-Temporal Transformer for Dynamic Scene Graph Generation, CVPR 2021.

**Comment by sayaknag** [comment]
Can you elaborate as to why mR@K over all frames is incorrect? I am unable to understand your rationale. PS the same evaluation code was also used for computing the mR@K of STTran as well in order to ensure an apples-to-apples comparison.

**Comment by sayaknag** [comment]
Additionally we took the mrecall@K code from https://github.com/KaihuaTang/VCTree-Scene-Graph-Generation/blob/master/lib/evaluation/sg_eval.py the paper that first introduced mR@K.
