### ISSUE TITLE
CUDA VERSION

### ISSUE THREAD

**Issue by fjscfy** [sayaknag/unbiasedSGG#5]
Hi, I would like to know if your code has any requirements for the CUDA version and what is the Python version of the environment.

**Comment by kylemin** [comment]
Sayak and I have tested the code with multiple versions of CUDA and Python, but we recommend using CUDA 11.1 and Python 3.6.

**Comment by fjscfy** [comment]
> Sayak and I have tested the code with multiple versions of CUDA and Python, but we recommend using CUDA 11.1 and Python 3.6.

thank you, I noticed that your method is based on STTran. The original author recommends CUDA 11.0 or below. Have you tested a version higher than 11.1? Or have you made some improvements in this area? This is really important to me, I look forward to your reply
